name: Keep Render Awake (Randomized)

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Random delay (0â€“5 minutes)
        run: |
          DELAY=$((RANDOM % 30000))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Ping Render app
        run: |
          curl -s https://my-unsent-backend.onrender.com//api/messages > /dev/null
